version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-efs-vpc"
s3_prefix = "lambda-efs-vpc"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
