# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Beginning AWS Lambda: An exercise in learning basics of Lambda.

Transform:
- AWS::Serverless-2016-10-31

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:

  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  getAwsDocsRepo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getAwsDocsRepo
      Handler: src/get-awsdocs-repo.handler
      Description: A Lambda that fetches AWS Docs repo from GitHub and uploads to S3.
      Environment:
        Variables:
          AWS_DOCS_REPO_BUCKET:
            Ref: awsDocsRepoBucketName
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess

  unzipRepoArchive:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: unzipRepoArchive
      Handler: src/unzip-repo-archive.handler
      Description: A Lambda that reads the AWS Docs repo in S3 GitHub and unzips it to EFS.
      Events:
        awsDocsRepoUpdate:
          Type: S3
          Properties:
            Bucket: !Ref awsDocsRepo
            Events:
              - s3:ObjectCreated:Put
              - s3:ObjectCreated:Post
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: aws-cloudformation-user-guide
                - Name: suffix
                  Value: zip
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 60
        MaximumRetryAttempts: 2
        DestinationConfig:
          OnSuccess:
            Type: SNS
            Destination: !Ref unzipRepoArchiveSuccessfulInvocationsDestination
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
        # - AWSLambdaVPCAccessExecutionRole
        # - AmazonElasticFileSystemClientFullAccess
      # FileSystemConfigs:
      # - Arn: arn:aws:elasticfilesystem:us-east-1:xxxxxx:access-point/xxxx-123abcdef12abcdef
      #   LocalMountPath: /mnt/efs

  unzipRepoArchiveSuccessfulInvocationsDestination:
    Type: "AWS::SNS::Topic"
    Properties:
      DisplayName: unzipRepoArchiveSuccessfulInvocations
      TopicName: unzipRepoArchiveSuccessfulInvocations

  awsDocsRepo:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName:
        Ref: awsDocsRepoBucketName
      AccessControl: Private

Globals:
  Function:
    CodeUri: sam-build/beginning-lambda.zip
    Runtime: nodejs12.x
    MemorySize: 256
    Timeout: 180
    Layers:
      - Fn::ImportValue:
          !Sub "${AwsSdkLayerStackName}-arn"

Parameters:
    awsDocsRepoBucketName:
      Description: Name of the S3 bucket to store AWS docomentation repo.
      Type: String
      AllowedPattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-5][0-9a-fA-F]{3}-[089abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
    AwsSdkLayerStackName:
      Description: Name of the Lambda layer with Node.js AWS SDK
      Type: String
      Default: layer-aws-sdk
