version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lib-aws-sdk"
s3_prefix = "lib-aws-sdk"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nasb5bg3gqu0"
