# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Beginning AWS Lambda: An exercise in learning basics of Lambda.

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  getAwsDocsRepo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getAwsDocsRepo
      Handler: src/get-awsdocs-repo.handler
      CodeUri: sam-build/beginning-lambda.zip
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda that fetches AWS Docs repo from GitHub and uploads to S3.
      Environment:
        Variables:
          AWS_DOCS_REPO_BUCKET:
            Ref: awsDocsRepoBucketName
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
      Layers:
        - Fn::ImportValue:
            !Sub "${AwsSdkLayerStackName}-arn"
  awsDocsRepo:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName:
        Ref: awsDocsRepoBucketName
      AccessControl: Private

Parameters:
    awsDocsRepoBucketName:
      Description: Name of the S3 bucket to store AWS docomentation repo.
      Type: String
      AllowedPattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-5][0-9a-fA-F]{3}-[089abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$
    AwsSdkLayerStackName:
      Description: Name of the Lambda layer with Node.js AWS SDK
      Type: String
      Default: layer-aws-sdk
